spring:
  h2:
    console:
      enabled: true
      path: /h2
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: true
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
